const swaggerAutogen = require("swagger-autogen")();
require("dotenv").config();
let HOST = process.env.HOST;
let PORT = process.env.PORT;
let base_url = process.env.base_url;
const doc = {
  info: {
    version: "2.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `${HOST}:${PORT}`,
  basePath: `${base_url}`,
  schemes: ["http", "https"],
  servers: [
    {
      url: `http:${HOST}:${PORT}/`,
      description: "Development server",
    },
    {
      url: "https://staging.gigantic-server.com/v1",
      description: "Staging server",
    },
    {
      url: "https://api.gigantic-server.com/v1",
      description: "Production server",
    },
  ],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account",
      },
    },
  },
  definitions: {
    Parents: {
      father: "Simon Doe",
      mother: "Marie Doe",
    },
    User: {
      name: "Jhon Doe",
      age: 29,
      parents: {
        $ref: "#/definitions/Parents",
      },
      diplomas: [
        {
          school: "XYZ University",
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: "XYZ Company",
          },
        },
      ],
    },
    AddUser: {
      $name: "Jhon Doe",
      $age: 29,
      about: "",
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./app.js"];
swaggerAutogen(outputFile, endpointsFiles, doc);
