const swaggerAutogen = require("swagger-autogen")();
require("dotenv").config();
let HOST = process.env.HOST;
let PORT = process.env.PORT;
let base_url = process.env.base_url;
const doc = {
  info: {
    version: "v1",
    title: "QPORTApi",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `${HOST}:${PORT}`,
  basePath: `${base_url}`,
  externalDocs: {
    description: " Link To Import API ",
    url: `${HOST}:${PORT}/` + "swagger",
  },
  schemes: ["http", "https"],
  servers: [
    {
      url: `http:${HOST}:${PORT}/`,
      description: "Development server",
    },
    {
      url: "https://staging.gigantic-server.com/v1",
      description: "Staging server",
    },
    {
      url: "https://api.gigantic-server.com/v1",
      description: "Production server",
    },
  ],
  consumes: [
    "application/json",
    "text/json",
    "application/json-patch+json",
    "application/*+json",
  ],
  produces: [
    "application/json",
    "text/json",
    "application/json-patch+json",
    "application/*+json",
  ],
  tags: [
    {
      name: "ActiveSurchargeRpt",
    },
    {
      name: "Ageing",
    },
    {
      name: "Alerts",
    },
    {
      name: "Area",
    },
    {
      name: "Auth",
    },
    {
      name: "BookingStatus",
    },
    {
      name: "CAN",
    },
    {
      name: "Capacity",
    },
    {
      name: "CommodityRate",
    },
    {
      name: "Country",
    },
    {
      name: "Commodity",
    },
    {
      name: "Company",
    },
    {
      name: "CreditNote",
    },
    {
      name: "Currency",
    },
    {
      name: "DailyBookingReport",
    },
    {
      name: "DeliveryOrder",
    },
    {
      name: "DischargeConfirmation",
    },
    {
      name: "DropDown",
    },
    {
      name: "EmailManagement",
    },
    {
      name: "Feedback",
    },
    {
      name: "FormPref",
    },
    {
      name: "Invoice",
    },
    {
      name: "LoadConfirmation",
    },
    {
      name: "Menu",
    },
    {
      name: "MessageCenter",
    },
    {
      name: "MyBooking",
    },
    {
      name: "MyContracts",
    },
    {
      name: "NHupload",
    },
    {
      name: "OTS",
    },
    {
      name: "PeriodicReport",
    },
    {
      name: "PeriodicRpt",
    },
    {
      name: "ProvBooking",
    },
    {
      name: "RebatAndDisc",
    },
    {
      name: "Receipt",
    },
    {
      name: "Region",
    },
    {
      name: "RequestRate",
    },
    {
      name: "RiverBL",
    },
    {
      name: "Role",
    },
    {
      name: "roe",
    },
    {
      name: "Sequence",
    },
    {
      name: "ServiceBL",
    },
    {
      name: "ShippingInst",
    },
    {
      name: "Signup",
    },
    {
      name: "SpotRate",
    },
    {
      name: "ServiceBL",
    },
    {
      name: "Terminal",
    },
    {
      name: "UserProfile",
    },
    {
      name: "UserRule",
    },
    {
      name: "ViewSchedule",
    },
    {
      name: "Vessel",
    },
    {
      name: "WorkFlow",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account",
      },
    },
  },
  definitions: {
    Parents: {
      father: "Simon Doe",
      mother: "Marie Doe",
    },
    User: {
      name: "Jhon Doe",
      age: 29,
      parents: {
        $ref: "#/definitions/Parents",
      },
      diplomas: [
        {
          school: "XYZ University",
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: "XYZ Company",
          },
        },
      ],
    },
    AddUser: {
      $name: "Jhon Doe",
      $age: 29,
      about: "",
    },
  },
};

const outputFile = "./swagger_output1.json";
const endpointsFiles = ["./app.js"];
swaggerAutogen(outputFile, endpointsFiles, doc);
