let res = {
    "mc_result": {
        "MC": [
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 50,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": "QP002",
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Receipt",
                "MENUFORM_URL": "/Finance/receipt",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 2,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Contracting",
                "MODULEMASTER_PK": 4,
                "MODULE_NAME": "Contracting",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 14,
                "MODULEMASTER_FK": 4,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Commodity Rates",
                "MENUFORM_URL": "/Contracting/CommodityRates",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 10,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Contracting",
                "MODULEMASTER_PK": 4,
                "MODULE_NAME": "Contracting",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 33,
                "MODULEMASTER_FK": 4,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Local Charges",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Contracting",
                "MODULEMASTER_PK": 4,
                "MODULE_NAME": "Contracting",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 36,
                "MODULEMASTER_FK": 4,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "My Contracts",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Contracting",
                "MODULEMASTER_PK": 4,
                "MODULE_NAME": "Contracting",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 38,
                "MODULEMASTER_FK": 4,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "My Rebates",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Contracting",
                "MODULEMASTER_PK": 4,
                "MODULE_NAME": "Contracting",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 57,
                "MODULEMASTER_FK": 4,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 7,
                "MENUFORM_NAME": "Renew my Contract",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Contracting",
                "MODULEMASTER_PK": 4,
                "MODULE_NAME": "Contracting",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 58,
                "MODULEMASTER_FK": 4,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Request a Rate",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Contracting",
                "MODULEMASTER_PK": 4,
                "MODULE_NAME": "Contracting",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 71,
                "MODULEMASTER_FK": 4,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Surcharges",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Documentation",
                "MODULEMASTER_PK": 5,
                "MODULE_NAME": "Documentation",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 24,
                "MODULEMASTER_FK": 5,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "File Upload",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Documentation",
                "MODULEMASTER_PK": 5,
                "MODULE_NAME": "Documentation",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 39,
                "MODULEMASTER_FK": 5,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "NHC Upload",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Documentation",
                "MODULEMASTER_PK": 5,
                "MODULE_NAME": "Documentation",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 60,
                "MODULEMASTER_FK": 5,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "River Bill of lading",
                "MENUFORM_URL": "Documents/RiverBillofLading",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 9,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Documentation",
                "MODULEMASTER_PK": 5,
                "MODULE_NAME": "Documentation",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 64,
                "MODULEMASTER_FK": 5,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Service BL",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Documentation",
                "MODULEMASTER_PK": 5,
                "MODULE_NAME": "Documentation",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 66,
                "MODULEMASTER_FK": 5,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Shipping Instructions",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 1,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Ageing Report",
                "MENUFORM_URL": "/Reports/AgeingReport",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 16,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Credit Note",
                "MENUFORM_URL": "/Finance/credit-note",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 30,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Invoice",
                "MENUFORM_URL": "/Finance/Invoice",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 42,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "Outstanding",
                "MENUFORM_URL": "/Reports/outstanding",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 44,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 8,
                "MENUFORM_NAME": "Periodic Report",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 48,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Rebates and Discounts",
                "MENUFORM_URL": "/Reports/RebateDiscount",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Finance",
                "MODULEMASTER_PK": 3,
                "MODULE_NAME": "Finance",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 69,
                "MODULEMASTER_FK": 3,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 7,
                "MENUFORM_NAME": "Statement of Accounts",
                "MENUFORM_URL": "/Reports/statementofaccount",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 7,
                "MODULE_ID": "My Documents",
                "MODULEMASTER_PK": 7,
                "MODULE_NAME": "My Documents",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 11,
                "MODULEMASTER_FK": 7,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Cargo Arrival Notice",
                "MENUFORM_URL": "/Documents/CargoArrivalNotice",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 7,
                "MODULE_ID": "My Documents",
                "MODULEMASTER_PK": 7,
                "MODULE_NAME": "My Documents",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 20,
                "MODULEMASTER_FK": 7,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Delivery Order",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 7,
                "MODULE_ID": "My Documents",
                "MODULEMASTER_PK": 7,
                "MODULE_NAME": "My Documents",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 31,
                "MODULEMASTER_FK": 7,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "Invoice",
                "MENUFORM_URL": "/Finance/Invoice",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 7,
                "MODULE_ID": "My Documents",
                "MODULEMASTER_PK": 7,
                "MODULE_NAME": "My Documents",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 51,
                "MODULEMASTER_FK": 7,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Receipt",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 7,
                "MODULE_ID": "My Documents",
                "MODULEMASTER_PK": 7,
                "MODULE_NAME": "My Documents",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 61,
                "MODULEMASTER_FK": 7,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "River Bill of lading",
                "MENUFORM_URL": "Documents/RiverBillofLading",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 7,
                "MODULE_ID": "My Documents",
                "MODULEMASTER_PK": 7,
                "MODULE_NAME": "My Documents",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 65,
                "MODULEMASTER_FK": 7,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Service BL",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Operations",
                "MODULEMASTER_PK": 1,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 10,
                "MODULEMASTER_FK": 1,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "Cargo Arrival Notice",
                "MENUFORM_URL": "/Documents/CargoArrivalNotice",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Operations",
                "MODULEMASTER_PK": 1,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 21,
                "MODULEMASTER_FK": 1,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Discharge Confirmation",
                "MENUFORM_URL": "/Operation/DischargeConfirmation",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Operations",
                "MODULEMASTER_PK": 1,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 27,
                "MODULEMASTER_FK": 1,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "HazMat Request",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Operations",
                "MODULEMASTER_PK": 1,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 32,
                "MODULEMASTER_FK": 1,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Load Confirmation",
                "MENUFORM_URL": "/Operation/LoadConfirmation",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Operations",
                "MODULEMASTER_PK": 1,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 52,
                "MODULEMASTER_FK": 1,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Reefer Request",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Operations",
                "MODULEMASTER_PK": 1,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 63,
                "MODULEMASTER_FK": 1,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Schedule",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "Order Management",
                "MODULEMASTER_PK": 2,
                "MODULE_NAME": "Order Management",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 5,
                "MODULEMASTER_FK": 2,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 7,
                "MENUFORM_NAME": "Ammend My Booking",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "Order Management",
                "MODULEMASTER_PK": 2,
                "MODULE_NAME": "Order Management",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 9,
                "MODULEMASTER_FK": 2,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Capacity",
                "MENUFORM_URL": "/OrderManagement/Capacity",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "Order Management",
                "MODULEMASTER_PK": 2,
                "MODULE_NAME": "Order Management",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 19,
                "MODULEMASTER_FK": 2,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Dashboard",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "Order Management",
                "MODULEMASTER_PK": 2,
                "MODULE_NAME": "Order Management",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 34,
                "MODULEMASTER_FK": 2,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "My Booking",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "Order Management",
                "MODULEMASTER_PK": 2,
                "MODULE_NAME": "Order Management",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 40,
                "MODULEMASTER_FK": 2,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "New Booking",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "Order Management",
                "MODULEMASTER_PK": 2,
                "MODULE_NAME": "Order Management",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 46,
                "MODULEMASTER_FK": 2,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "Provisional Booking",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "Order Management",
                "MODULEMASTER_PK": 2,
                "MODULE_NAME": "Order Management",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 73,
                "MODULEMASTER_FK": 2,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Upload Prospects",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 6,
                "MODULE_ID": "Reports",
                "MODULEMASTER_PK": 6,
                "MODULE_NAME": "Reports",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 2,
                "MODULEMASTER_FK": 6,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "Ageing Report",
                "MENUFORM_URL": "/Reports/AgeingReport",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 6,
                "MODULE_ID": "Reports",
                "MODULEMASTER_PK": 6,
                "MODULE_NAME": "Reports",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 8,
                "MODULEMASTER_FK": 6,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Booking Status",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 6,
                "MODULE_ID": "Reports",
                "MODULEMASTER_PK": 6,
                "MODULE_NAME": "Reports",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 18,
                "MODULEMASTER_FK": 6,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Daily Booking Report",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 6,
                "MODULE_ID": "Reports",
                "MODULEMASTER_PK": 6,
                "MODULE_NAME": "Reports",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 43,
                "MODULEMASTER_FK": 6,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Outstanding",
                "MENUFORM_URL": "/Reports/outstanding",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 6,
                "MODULE_ID": "Reports",
                "MODULEMASTER_PK": 6,
                "MODULE_NAME": "Reports",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 45,
                "MODULEMASTER_FK": 6,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 7,
                "MENUFORM_NAME": "Periodic Report",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 6,
                "MODULE_ID": "Reports",
                "MODULEMASTER_PK": 6,
                "MODULE_NAME": "Reports",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 49,
                "MODULEMASTER_FK": 6,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Rebates and Discounts",
                "MENUFORM_URL": "/Reports/RebateDiscount",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 6,
                "MODULE_ID": "Reports",
                "MODULEMASTER_PK": 6,
                "MODULE_NAME": "Reports",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "MC",
                "MENUMASTERFORM_PK": 70,
                "MODULEMASTER_FK": 6,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Statement of Accounts",
                "MENUFORM_URL": "/Reports/statementofaccount",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            }
        ],
        "HC": [
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Communications",
                "MODULEMASTER_PK": 10,
                "MODULE_NAME": "Communications",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 4,
                "MODULEMASTER_FK": 10,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Alerts",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Communications",
                "MODULEMASTER_PK": 10,
                "MODULE_NAME": "Communications",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 6,
                "MODULEMASTER_FK": 10,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Announcements",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Communications",
                "MODULEMASTER_PK": 10,
                "MODULE_NAME": "Communications",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 12,
                "MODULEMASTER_FK": 10,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Chat",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Communications",
                "MODULEMASTER_PK": 10,
                "MODULE_NAME": "Communications",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 23,
                "MODULEMASTER_FK": 10,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "Feedback",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Communications",
                "MODULEMASTER_PK": 10,
                "MODULE_NAME": "Communications",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 29,
                "MODULEMASTER_FK": 10,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "In-Box",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 3,
                "MODULE_ID": "Communications",
                "MODULEMASTER_PK": 10,
                "MODULE_NAME": "Communications",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 41,
                "MODULEMASTER_FK": 10,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Notifications",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "HC_Operations",
                "MODULEMASTER_PK": 9,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 53,
                "MODULEMASTER_FK": 9,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Reg de Entrada",
                "MENUFORM_URL": "/HelpCenter/reg-de-entrada?Type=Entrada",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "HC_Operations",
                "MODULEMASTER_PK": 9,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 54,
                "MODULEMASTER_FK": 9,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Reg.De.Salida",
                "MENUFORM_URL": "/HelpCenter/reg-de-entrada?Type=Salida",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 2,
                "MODULE_ID": "HC_Operations",
                "MODULEMASTER_PK": 9,
                "MODULE_NAME": "Operations",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 62,
                "MODULEMASTER_FK": 9,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "River Draft",
                "MENUFORM_URL": "/HelpCenter/river-draft",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Information",
                "MODULEMASTER_PK": 8,
                "MODULE_NAME": "Information",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 3,
                "MODULEMASTER_FK": 8,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Agents",
                "MENUFORM_URL": "/HelpCenter/Agents",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Information",
                "MODULEMASTER_PK": 8,
                "MODULE_NAME": "Information",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 7,
                "MODULEMASTER_FK": 8,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "Asset List",
                "MENUFORM_URL": "/HelpCenter/AssetList",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Information",
                "MODULEMASTER_PK": 8,
                "MODULE_NAME": "Information",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 13,
                "MODULEMASTER_FK": 8,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Commodity",
                "MENUFORM_URL": "/HelpCenter/Commodity",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Information",
                "MODULEMASTER_PK": 8,
                "MODULE_NAME": "Information",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 15,
                "MODULEMASTER_FK": 8,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "Container Types",
                "MENUFORM_URL": "/HelpCenter/ContainerTypes",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Information",
                "MODULEMASTER_PK": 8,
                "MODULE_NAME": "Information",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 26,
                "MODULEMASTER_FK": 8,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Guaran Feeder",
                "MENUFORM_URL": "/HelpCenter/GuaranFeeder",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Information",
                "MODULEMASTER_PK": 8,
                "MODULE_NAME": "Information",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 47,
                "MODULEMASTER_FK": 8,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 7,
                "MENUFORM_NAME": "Rate of Exchanges",
                "MENUFORM_URL": "/HelpCenter/rateofExchange",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 1,
                "MODULE_ID": "Information",
                "MODULEMASTER_PK": 8,
                "MODULE_NAME": "Information",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 72,
                "MODULEMASTER_FK": 8,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Terminals",
                "MENUFORM_URL": "/HelpCenter/Terminal",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Support",
                "MODULEMASTER_PK": 11,
                "MODULE_NAME": "Support",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 17,
                "MODULEMASTER_FK": 11,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Customer Support",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 1,
                "MENUTOOLTIP": "Customer Support"
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Support",
                "MODULEMASTER_PK": 11,
                "MODULE_NAME": "Support",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 22,
                "MODULEMASTER_FK": 11,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "FAQ",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Support",
                "MODULEMASTER_PK": 11,
                "MODULE_NAME": "Support",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 25,
                "MODULEMASTER_FK": 11,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Glossary",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 4,
                "MODULE_ID": "Support",
                "MODULEMASTER_PK": 11,
                "MODULE_NAME": "Support",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 28,
                "MODULEMASTER_FK": 11,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Help",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Tool Kit",
                "MODULEMASTER_PK": 12,
                "MODULE_NAME": "Tool Kit",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 35,
                "MODULEMASTER_FK": 12,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 5,
                "MENUFORM_NAME": "My Company",
                "MENUFORM_URL": "/HelpCenter/mycompany",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 1,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Tool Kit",
                "MODULEMASTER_PK": 12,
                "MODULE_NAME": "Tool Kit",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 37,
                "MODULEMASTER_FK": 12,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 4,
                "MENUFORM_NAME": "My Profile",
                "MENUFORM_URL": "/register",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 1,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Tool Kit",
                "MODULEMASTER_PK": 12,
                "MODULE_NAME": "Tool Kit",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 55,
                "MODULEMASTER_FK": 12,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 1,
                "MENUFORM_NAME": "Register",
                "MENUFORM_URL": "/register",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Tool Kit",
                "MODULEMASTER_PK": 12,
                "MODULE_NAME": "Tool Kit",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 56,
                "MODULEMASTER_FK": 12,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 7,
                "MENUFORM_NAME": "Remove Me",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 1,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Tool Kit",
                "MODULEMASTER_PK": 12,
                "MODULE_NAME": "Tool Kit",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 59,
                "MODULEMASTER_FK": 12,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 6,
                "MENUFORM_NAME": "Reset Password",
                "MENUFORM_URL": "/under-construction",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 1,
                "MENUTOOLTIP": null
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Tool Kit",
                "MODULEMASTER_PK": 12,
                "MODULE_NAME": "Tool Kit",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 67,
                "MODULEMASTER_FK": 12,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 3,
                "MENUFORM_NAME": "Sign-up for Alerts",
                "MENUFORM_URL": "/register?value=alerts",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": "Sign-up for Alerts"
            },
            {
                "MODMENU_SORT_ORDER": 5,
                "MODULE_ID": "Tool Kit",
                "MODULEMASTER_PK": 12,
                "MODULE_NAME": "Tool Kit",
                "MODULE_IMAGE": null,
                "MOD_CATEGORY": "HC",
                "MENUMASTERFORM_PK": 68,
                "MODULEMASTER_FK": 12,
                "MENUFORM_ID": null,
                "MENUFORM_SORT_ORDER": 2,
                "MENUFORM_NAME": "Sign-up for Notifications",
                "MENUFORM_URL": "/register?value=notifications",
                "MENUFORM_IMAGE": null,
                "FEATUREFORM_FK": 0,
                "FORMMASTER_FK": 0,
                "ACCESSFLAG": 0,
                "MENUTOOLTIP": "Sign-up for Notifications"
            }
        ]
    }
};

let MCData = res.mc_result["MC"]

// let sortedData = MCData.sort(dynamicSort("MODMENU_SORT_ORDER"))

let sortedData = sortByKey(MCData, "MODMENU_SORT_ORDER")

console.log(sortedData)
function dynamicSort(property) {
    var sortOrder = 1;

    if(property[0] === "-") {
        sortOrder = -1;
        property = property.substr(1);
    }

    return function (a,b) {
        if(sortOrder == -1){
            return b[property].localeCompare(a[property]);
        }else{
            return a[property].localeCompare(b[property]);
        }        
    }
}

function sortByKey(array, key) {
    return array.sort((a, b) => {
      let x = a[key];
      let y = b[key];
      
      return ((x < y) ? -1 : ((x > y) ? 1 : 0));
    });
  }