const Joi = require("joi");
const schemas = {
  fetchDDCarrierSchema: Joi.object().keys({
    userfk: Joi.number(),
  }),

  fetchDDLocationSchema: Joi.object().keys({
    userfk: Joi.number().required(),
    carrierpk: Joi.number().required(),
    fromdate: Joi.string().allow(""),
    customerfk: Joi.number(),
    todate: Joi.string().allow(""),
  }),
  fetchDDVoyageSchema: Joi.object().keys({
    userfk: Joi.number().required(),
    carrierpk: Joi.number().required(),
    locfks: Joi.string().allow(""),
    fromdate: Joi.string().allow(""),
    customerfk: Joi.number(),
    todate: Joi.string().allow(""),
  }),

  fetchDDCustomerSchema: Joi.object().keys({
    userfk: Joi.number().required(),
    carrierpk: Joi.number().required(),
    locfks: Joi.string().allow(""),
    fromdate: Joi.string().allow(""),
    cshfks: Joi.string().allow(""),
    customerfk: Joi.number(),
    todate: Joi.string().allow(""),
  }),
  fetchDDInvoiceSchema: Joi.object().keys({
    userfk: Joi.number().required(),
    carrierpk: Joi.number().required(),
    locfks: Joi.string().allow(""),
    fromdate: Joi.string().allow(""),
    customerfks: Joi.string().allow(""),
    invoicefks: Joi.string().allow(""),
    cshfks: Joi.string().allow(""),
    customerfk: Joi.number(),
    todate: Joi.string().allow(""),
  }),
  fetchOTS_InvoiceListSchema: Joi.object().keys({
    userfk: Joi.number().required(),
    carrierpk: Joi.number().required(),
    locfks: Joi.string().allow(""),
    fromdate: Joi.string().allow(""),
    customerfks: Joi.string().allow(""),
    invoicefks: Joi.string().allow(""),
    cshfks: Joi.string().allow(""),
    customerfk: Joi.number(),
    invoice_mst_pk: Joi.number(),
    todate: Joi.string().allow(""),
    customermasterpk: Joi.string().allow(""),
    invoicenr: Joi.string().allow(""),
    inv_date: Joi.string().allow(""),
    customername: Joi.string().allow(""),
    bookingid: Joi.string().allow(""),
    po_number: Joi.string().allow(""),
    vslvoy: Joi.string().allow(""),
    pol: Joi.string().allow(""),
    polterminal: Joi.string().allow(""),
    pod: Joi.string().allow(""),
    podterminal: Joi.string().allow(""),
    currency: Joi.string().allow(""),
    tax_amount: Joi.number(),
    total_amount: Joi.number(),
    qport_pdf_path:Joi.string().allow(""),
  }),
};
module.exports = schemas;
